### ISSUE TITLE
Maven repo appears to be down.

### ISSUE THREAD

**Issue by samuelh2005** [Mangolise/mango-game-sdk#1]
It appears your Maven repo (`https://maven.serble.net/snapshots/`) is down as when I try to acess it I get a "502 Bad Gateway" error and Gradle is unable to download the Mango Game SDK.

![image](https://github.com/user-attachments/assets/864b2b6d-bd2c-4e17-a180-31c522010d10)

**Comment by CoPokBl** [comment]
You are correct, sorry about that. It seems as though there was a power outage and the maven server failed to recover correctly.

It is back online and I'll look into fixing the restarting issue.

*Edit: The maven repo should now handle restarts correctly.*
